---
title: "Performance-measures"
format: pdf
editor: visual
---

## Performance measures

This project has two performance measures: type I and type II error for the estimand $\beta_1$.

### Type I

The type I error refers to a false-positive, or rejecting the null-hypothesis when it is true. In this study that would mean detecting an effect in the no-effect scenario. Type I error is generally acceptable at a rate of 5% or below, based on an alpha level of .05. In this case, a rate of higher than 5% is considered an inflated type I error rate. Thus, the type I error is measured in the amount of cases in the no-effect scenario with a p-value lower than .05 for each specific condtion.

### Type II

Type II error refers to a false negative, or failing to reject the null-hypothesis when it is false. In this study that would mean failing to detect an effect in the effect scenario. Type II error is commonly assessed in the form of power. Power is $1-\beta$, where $\beta$ is the type II error. The nominal type II error rate of .20 results in a generally accepted power level of 80%. Consequently, in this study, power rates of below 80% are considered an inflated type II error rate. Thus, type II error is measured in the amount of cases in the effect scenario with a p-value higher than .05 for each specific condition.
